# Netlify: build a static export of Next.js and publish /out.

[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  # Node 20 is recommended for Next 14; 18 also works.
  NODE_VERSION = "20"

# Optional: small serverless functions live here (only if you add any).
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cache static assets produced by Next export.
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Make both /thank-you and /thank-you/ work.
[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 200
