# Netlify: build a static export of Next.js and publish /out.
# No Next.js plugin, no large server handler.

[build]
  command = "yarn build"
  publish = "out"
  # (Optional but recommended) lock Node version used on Netlify
  environment = { NODE_VERSION = "18" }

# Use a small functions folder for things like Airtable/Email.
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cache static assets produced by Next export.
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
