# Netlify: build a static export of Next.js and publish /out.

[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  # Use Node 20 and DISABLE Netlify's Next runtime
  NODE_VERSION = "20"
  NETLIFY_USE_NEXT_RUNTIME = "false"

# Cache static assets from Next
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force static thank-you page for both URL shapes
[[redirects]]
  from = "/thank-you"
  to = "/thank-you/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/thank-you/"
  to = "/thank-you/index.html"
  status = 200
  force = true
