backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: homepage
    label: Homepage
    editor:
      preview: false
    files:
      - file: data/homepage.json
        label: Homepage Content
        name: homepage
        format: json
        fields:
          - label: Hero Headline
            name: hero_headline
            widget: string
          - label: Hero Subheadline
            name: hero_subheadline
            widget: text
          - label: About Headline
            name: about_headline
            widget: string
          - label: About Text
            name: about_text
            widget: text
          - label: About Image
            name: about_image
            widget: image

  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - file: data/settings.json
        label: Business Settings
        name: settings
        format: json
        fields:
          - label: Phone
            name: phone
            widget: string
          - label: Email
            name: email
            widget: string
          - label: Facebook URL
            name: facebook_url
            widget: string
            required: false
          - label: Service Area
            name: service_area
            widget: string

  - name: menu
    label: Menu Cards
    label_singular: Menu Card
    folder: data/menu
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    summary: "{{title}} - {{price}}"
    sortable_fields:
      - title
      - price
      - commit_date
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Price (display text)
        name: price
        widget: string
      - label: Items
        name: items
        widget: list
      - label: Image
        name: image
        widget: image
        required: false

  - name: gallery
    label: Gallery
    folder: data/gallery
    create: true
    format: frontmatter
    extension: md
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: false
      - label: Image
        name: image
        widget: image

  - name: testimonials
    label: Testimonials
    folder: data/testimonials
    create: true
    format: frontmatter
    extension: md
    slug: "{{slug}}"
    summary: "{{name}} - {{quote}}"
    fields:
      - label: Name
        name: name
        widget: string
      - label: Quote
        name: quote
        widget: text
      - label: Avatar
        name: avatar
        widget: image
        required: false

  - name: faq
    label: FAQ
    folder: data/faq
    create: true
    format: frontmatter
    extension: md
    slug: "{{slug}}"
    summary: "Q: {{question}}"
    fields:
      - label: Question
        name: question
        widget: string
      - label: Answer
        name: answer
        widget: text

  - name: help
    label: Help
    editor:
      preview: false
    files:
      - file: data/help.md
        label: Editor Guide
        name: guide
        format: frontmatter
        fields:
          - label: Title
            name: title
            widget: string
            default: Welcome to your editor
          - label: Guide
            name: body
            widget: markdown
