backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "site"
    label: "Site Settings"
    editor: { preview: false }
    files:
      - file: "content/site.json"
        label: "Business Info"
        name: "general"
        fields:
          - { label: "Business Name", name: "businessName", widget: "string", hint: "Shown in header & SEO." }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Service Area", name: "serviceArea", widget: "string" }
          - { label: "Instagram URL", name: "instagram", widget: "string", required: false }
          - { label: "Facebook URL", name: "facebook", widget: "string", required: false }

  - name: "menus"
    label: "Menus"
    label_singular: "Menu"
    folder: "content/menus"
    create: true
    sortable_fields: ["title", "basePrice", "serves", "commit_date"]
    view_groups:
      - { label: "Serves", field: "serves" }
    summary: "{{title}} — ${{basePrice}} · serves {{serves}}"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "e.g., Small Grazing Board" }
      - { label: "Description", name: "description", widget: "text", hint: "What makes this board special?" }
      - { label: "Base Price ($)", name: "basePrice", widget: "currency", value_type: "float", min: 0, step: 0.01 }
      - { label: "Serves", name: "serves", widget: "number", min: 1, step: 1 }
      - { label: "Photo", name: "image", widget: "image", required: false, hint: "Landscape image works best." }
      - label: "Add‑ons"
        name: "addons"
        widget: "list"
        required: false
        summary: "{{fields.name}} — ${{fields.price}}"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Price ($)", name: "price", widget: "currency", value_type: "float", min: 0, step: 0.01 }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    summary: "{{caption}}"
    fields:
      - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
